companieshouse/chs-notification-sender-api

pom.xml, src/main/java/uk/gov/companieshouse/chs/notification/sender/api/restapi/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/chs/notification/sender/api/restapi/LoggingInterceptor.java, src/main/java/uk/gov/companieshouse/chs/notification/sender/api/restapi/StaticPropertyUtil.java
Implementing api security using InternalUserInterceptor which validates the api keys from the request headers
=> Deep 203 implementing api security

ecs-image-build/docker_start.sh, pom.xml
SPringBootApplication run was failing due to docker compose file not found, to fix this - 
* removed docker compose from dependencies
* also removed duplicate entries
=> PR to fix application run

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/variables.tf
investigating issue with phoenix1 plan concourse job which isn't picking up service version. Adjusting tf code to match similar service.
=> adjusting dashes to underscore

terraform/groups/ecs-service/locals.tf
Updated the stack_name to notifications
=> changing stack to notifications

pom.xml, src/main/java/uk/gov/companieshouse/chs/notification/sender/api/kafka/KafkaProducerInterface.java, src/main/java/uk/gov/companieshouse/chs/notification/sender/api/restapi/NotificationController.java, src/main/java/uk/gov/companieshouse/chs/notification/sender/api/translator/EmailDetailsRequest.java, src/main/java/uk/gov/companieshouse/chs/notification/sender/api/translator/LetterDetailsRequest.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/restapi/NotificationControllerTests.java, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/utils/NotificationTestDataManager.java
DEEP-259
update to use latest swagger spec
=> update to use latest swagger spec

pom.xml, rest-client.http, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/restapi/NotificationControllerTests.java, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/utils/NotificationTestDataManager.java
No JIRA
update private-api dependency version
=> update private-api dependency version

pom.xml, src/main/java/uk/gov/companieshouse/chs/notification/sender/api/translator/KafkaTranslatorService.java, src/main/java/uk/gov/companieshouse/chs/notification/sender/api/translator/NotificationMapper.java, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/translator/KafkaTranslatorServiceTest.java
__DEEP-207__
updating model classes and mappers based on the latest schema changes
=> DEEP-207 updating sender api with schema changes

terraform/groups/ecs-service/locals.tf
=> updating vpc name variable

terraform/groups/ecs-service/locals.tf
=> changing lb

README.md, docker-compose.yaml
add kafka docker container to README
=> :sparkles: add kafka docker container to README

src/main/resources/application.properties, terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars, terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars, terraform/groups/ecs-service/variables.tf
checking over tf changes in comparison with other successfully deployed services with @askinner-ch
=> tf, docker and hc changes

terraform/groups/ecs-service/locals.tf
=> Modifying the listener path

src/main/java/uk/gov/companieshouse/chs/notification/sender/api/config/SecurityConfig.java, src/main/resources/application.properties, src/test/resources/application.properties
* [ x ] Bug fix
* [ x ] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)
=> set the api security path explicitly

src/main/resources/application.properties, terraform/groups/ecs-service/locals.tf
- Refactor => updating the healthcheck to match CH standards and hit the correct endpoint (not the generic phoenix 1 check) 
See attached status:
=> Updating healthcheck endpoint

pom.xml
Adding of sonarqube properties for the pipeline checks.
=> BAU: updating for sonarqube details

src/main/java/uk/gov/companieshouse/chs/notification/sender/api/kafka/KafkaProducerService.java, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/interceptor/LoggingInterceptorTest.java
=> fix unused and duplicated imports

src/main/java/uk/gov/companieshouse/chs/notification/sender/api/controller/NotificationSenderController.java, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/controller/NotificationSenderControllerTest.java, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/health/HealthCheckControllerTest.java, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/kafka/KafkaProducerServiceTest.java
=> Resolve 26 sonarcube issues

api-collections/bruno/chs-notification-sender-api/requests/Send New PSC Direction Letter.bru
__DEEP-354 WIP__
__Update fields used for the  New PSC Direction Letter as agreed. See [DEEP-354: Update variables used for New PSC Direction Letter template as agreed](https://github.com/companieshouse/chs-gov-uk-notify-integration-api/pull/56) for details.__
=> DEEP-354: Update variables used for New PSC Direction Letter template as agreed

api-collections/bruno/chs-notification-sender-api/requests/Send Transitional Non-director PSC Information Letter.bru, api-collections/bruno/chs-notification-sender-api/requests/sendEmail.bru, pom.xml
__DEEP-268__
* __Add Bruno test request for the Transitional Non-director PSC Information Letter.__
* __Avoid reported security vulnerabilities.__
=> DEEP-268: Add Transitional Non-director PSC Information Letter request

api-collections/bruno/chs-notification-sender-api/requests/Send Extension Acceptance Letter.bru, api-collections/bruno/chs-notification-sender-api/requests/sendEmail.bru, pom.xml
__DEEP-414__
* __Add Bruno test request for the Extension Acceptance Letter.__
* __Avoid security vulnerabilities.__
=> DEEP-414: Add Extension Acceptance Letter request

api-collections/bruno/chs-notification-sender-api/requests/Send Welsh Extension Acceptance Letter.bru, api-collections/bruno/chs-notification-sender-api/requests/sendEmail.bru
__Add Bruno test request for the Welsh Extension Acceptance Letter.__
=> DEEP-376: Add Welsh Extension Acceptance Letter request

pom.xml
__DEEP-454__
* __Make upgrades to dependencies to avoid vulnerabilities:__
* CVE-2025-48924
* CVE-2024-11407
* CVE-2024-7246
* CVE-2025-53864. 
* __Compare `dependency-check` [before](https://ci-platform.companieshouse.gov.uk/teams/team-development/pipelines/chs-notification-sender-api/jobs/dependency-check/builds/112) and [after](https://ci-platform.companieshouse.gov.uk/teams/team-development/pipelines/chs-notification-sender-api/jobs/dependency-check/builds/113) these changes.__  
=> DEEP-454: Security vulnerabilities

src/main/java/uk/gov/companieshouse/chs/notification/sender/api/controller/NotificationSenderController.java, src/main/java/uk/gov/companieshouse/chs/notification/sender/api/kafka/KafkaProducerService.java, src/test/java/helpers/OutputCapture.java, src/test/java/helpers/utils/OutputAssertions.java, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/controller/NotificationSenderControllerTest.java, src/test/java/uk/gov/companieshouse/chs/notification/sender/api/kafka/KafkaProducerServiceTest.java
https://companieshouse.atlassian.net/browse/DEEP-297
Changed logs so that they use [DataMap.Builder](https://github.com/companieshouse/structured-logging/blob/main/src/main/java/uk/gov/companieshouse/logging/util/DataMap.java) from [structured logging](https://github.com/companieshouse/structured-logging)
=> Task/deep 297 tech debt   refactor application logging to use structured logging

src/test/java/uk/gov/companieshouse/chs/notification/sender/api/controller/NotificationSenderControllerTest.java
Remove unused import missed in https://github.com/companieshouse/chs-notification-sender-api/pull/76
=> Remove unused import

api-collections/bruno/chs-notification-sender-api/requests/Send CSIDVDEF Letter.bru, api-collections/bruno/chs-notification-sender-api/requests/Send IDVPSDEFAULT Letter.bru
Add bruno files for IDV default letters
=> Add bruno files for IDV default letters

api-collections/bruno/chs-notification-sender-api/requests/Send Welsh Second Extension Acceptance Letter.bru, api-collections/bruno/chs-notification-sender-api/requests/sendEmail.bru
__DEEP-497__
__Add Bruno test request for the (bilingual) Welsh Second Extension Acceptance Letter.__
=> DEEP-497: Add Welsh Second Extension Acceptance Letter request
